spring:
  application:
    name: lingdaoyi-transfer-api
    
server:
  port: 10816
logging:
  level:
    root: INFO
    org.hibernate: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.type.descriptor.sql.BasicExtractor: TRACE
    com.itmuch: DEBUG
eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://user:password123@localhost:10810/eureka
#      defaultZone: http://user:password123@localhost:10810/lingdaoyi-eureka/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ipAddress}:${spring.application.instance_id:${server.port}}
hystrix:  
  command:  
      default:  
        execution:  
          isolation:  
            thread:  
              timeoutInMilliseconds: 5000
mybatis:
    type-aliases-package: com.lingdaoyi.cloud.entity
    mapper-locations: classpath:mapper/*.xml

mapper:
    mappers:
        - com.lingdaoyi.cloud.baseMapper.BaseMapper
    not-empty: false
    identity: MYSQL

pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql